let currentApprovalId = null;
let lastState = {};
const $ = (id) => document.getElementById(id);
const providers = globalThis.AWB_PROVIDERS || [];
const utils = globalThis.AWB_PROVIDER_UTILS;

function addLog(label, text) {
  const timeline = $("timeline");
  const item = document.createElement("div"); item.className = "timeline-item";
  const b = document.createElement("b"); b.textContent = label;
  const span = document.createElement("span"); span.textContent = text;
  item.append(b, span); timeline.prepend(item);
  while (timeline.children.length > 80) timeline.lastChild.remove();
}

async function command(action, extra = {}) {
  return chrome.runtime.sendMessage({ type: "BRIDGE_COMMAND", payload: { action, ...extra } });
}

function selectedProvider() { return utils.getProvider($("providerId").value) || providers[0]; }
function populateProviders() { $("providerId").replaceChildren(); for (const p of providers) { const option = document.createElement("option"); option.value = p.id; option.textContent = `${p.name} — ${p.status.toUpperCase()}`; $("providerId").append(option); } }
function updateProviderCard(provider = selectedProvider()) {
  $("providerName").textContent = provider.name; $("providerStatus").textContent = provider.status.toUpperCase();
  const notes = { stable: "Stable adapter. Still stops on provider security/rate-limit signals.", beta: "Beta web adapter: selectors can change when the provider updates its UI.", experimental: "Experimental adapter: verify the first few turns manually before long runs." };
  $("providerSafetyNote").textContent = `${notes[provider.status] || notes.beta} The Bridge never automates login or exports your session.`;
  $("activeProvider").textContent = provider.name.toUpperCase().slice(0, 13);
  const model = $("modelLabel")?.value?.trim(); $("providerDetail").textContent = model || ($("providerAuto").checked ? "Auto-detect active tab" : `${provider.status} adapter`);
}
async function providerForActiveTab() { const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); const tab = tabs[0]; if (!tab?.url) return null; try { return utils.detectProvider(new URL(tab.url).hostname); } catch { return null; } }
async function effectiveProvider() { if (!$("providerAuto").checked) return selectedProvider(); const p = await providerForActiveTab(); if (!p) throw new Error("The active tab is not a supported LLM. Open one of the supported web LLMs first."); return p; }
async function grantProviderAccess({ quiet = false } = {}) { const provider = await effectiveProvider(); const contains = await chrome.permissions.contains({ origins: provider.origins }); if (contains) { if (!quiet) addLog("SAFE", `${provider.name} site access is already granted.`); return provider; } const granted = await chrome.permissions.request({ origins: provider.origins }); if (!granted) throw new Error(`Site access for ${provider.name} was not granted.`); addLog("UNLOCK", `Granted site access only for ${provider.name}.`); return provider; }
function numberValue(id, fallback) { const value = Number($(id).value); return Number.isFinite(value) ? value : fallback; }
function gatherConfig() { return { project_name: $("projectName").value.trim(), project_goal: $("projectGoal").value.trim(), workspace_root: $("workspaceRoot").value.trim(), provider_mode: $("providerAuto").checked ? "auto" : "manual", provider_id: $("providerId").value, model_label: $("modelLabel").value.trim(), auto_run_low_risk: $("autoRunLowRisk").checked, min_turn_interval_seconds: numberValue("minTurnInterval", 8), max_turns_per_hour: numberValue("maxTurnsHour", 20), max_turns_per_session: numberValue("maxTurnsSession", 25), max_runtime_minutes: numberValue("maxRuntimeMinutes", 90), bot_token: $("botToken").value.trim(), chat_id: $("chatId").value.trim() }; }
async function saveProject({ log = true } = {}) { const config = gatherConfig(); await command("save_config", { config }); if (log) addLog("SAVED", "Project, AI Engine, and safety limits saved locally."); }
function showApproval(event) { currentApprovalId = event.approval_id; $("approvalSummary").textContent = event.summary || "A protected action needs your approval."; $("approvalCommand").textContent = event.command || event.details || ""; $("approvalImpact").textContent = event.impact || "The workflow is paused until you decide."; $("approvalPanel").classList.remove("hidden"); }
function setLifecycleButtons(state) { const lifecycle = state.lifecycle || state.status || "setup"; $("armWorkflow").disabled = !["ready_to_arm", "idle", "paused", "protocol_error"].includes(lifecycle) && lifecycle !== "setup"; $("finishProject").disabled = ["setup", "planning", "complete"].includes(lifecycle); }
function fillConfig(config) { if (config.project_name != null) $("projectName").value = config.project_name; if (config.project_goal != null) $("projectGoal").value = config.project_goal; if (config.workspace_root != null) $("workspaceRoot").value = config.workspace_root; if (config.provider_id && utils.getProvider(config.provider_id)) $("providerId").value = config.provider_id; if (config.model_label != null) $("modelLabel").value = config.model_label; $("providerAuto").checked = config.provider_mode === "auto"; $("autoRunLowRisk").checked = config.auto_run_low_risk !== false; if (config.min_turn_interval_seconds != null) $("minTurnInterval").value = config.min_turn_interval_seconds; if (config.max_turns_per_hour != null) $("maxTurnsHour").value = config.max_turns_per_hour; if (config.max_turns_per_session != null) $("maxTurnsSession").value = config.max_turns_per_session; if (config.max_runtime_minutes != null) $("maxRuntimeMinutes").value = config.max_runtime_minutes; if (config.bot_configured && !$("botToken").value) $("botToken").placeholder = "Configured locally — enter only to replace"; if (config.chat_id != null) $("chatId").value = config.chat_id; updateProviderCard(); }
function fillBudget(budget = {}, config = {}) { $("budgetTurns").textContent = `${budget.session_turns || 0} / ${config.max_turns_per_session || 25}`; $("budgetHour").textContent = `${budget.turns_last_hour || 0} / ${config.max_turns_per_hour || 20}`; $("budgetRuntime").textContent = `${Math.round(budget.runtime_minutes || 0)} / ${config.max_runtime_minutes || 90}m`; $("budgetCooldown").textContent = budget.cooldown_until ? "PAUSED" : "READY"; }
function handleEvent(event) { if (!event) return; if (event.kind === "host_status") { $("hostStatus").textContent = event.connected ? "ONLINE" : "OFFLINE"; $("hostStatusDetail").textContent = event.text || "Native Messaging"; addLog(event.connected ? "KAPOW" : "UH-OH", event.text || "Host status changed"); } else if (event.kind === "state") { const state = event.state || {}; lastState = state; const lifecycle = state.lifecycle || state.status || "setup"; $("runStatus").textContent = String(lifecycle).replaceAll("_", " ").toUpperCase(); $("runStatusDetail").textContent = state.current_step || "No active workflow"; fillConfig(state.config || {}); fillBudget(state.budget || {}, state.config || {}); setLifecycleButtons(state); if (state.active_provider_name) { $("activeProvider").textContent = state.active_provider_name.toUpperCase().slice(0,13); $("providerDetail").textContent = "active browser adapter"; } } else if (event.kind === "approval_required") { showApproval(event); addLog("WAIT!", event.summary || "Approval required"); } else if (event.kind === "approval_resolved") { $("approvalPanel").classList.add("hidden"); currentApprovalId = null; addLog("DECIDED", `${event.decision || "decision"}: ${event.summary || "approval resolved"}`); } else if (event.kind === "step") { $("runStatus").textContent = (event.status || "RUNNING").replaceAll("_", " ").toUpperCase(); $("runStatusDetail").textContent = event.title || event.text || "Workflow step"; addLog(event.badge || "BAM", event.text || event.title || "Step update"); } else if (event.kind === "error") { $("runStatus").textContent = "PAUSED"; $("runStatusDetail").textContent = event.text || "Workflow error"; addLog("CRASH", event.text || "Unknown error"); } else if (event.kind === "info") addLog(event.badge || "INFO", event.text || "Update"); }
chrome.runtime.onMessage.addListener((message) => { if (message?.type === "BRIDGE_EVENT") handleEvent(message.payload); });
populateProviders(); $("providerId").value = "chatgpt"; updateProviderCard(); $("providerId").addEventListener("change", updateProviderCard); $("providerAuto").addEventListener("change", updateProviderCard); $("modelLabel").addEventListener("input", updateProviderCard); $("grantProvider").addEventListener("click", () => grantProviderAccess().catch((e) => addLog("NOPE", e.message))); $("saveConfig").addEventListener("click", () => saveProject().then(() => setTimeout(() => command("get_state"), 200)).catch((e) => addLog("CRASH", e.message)));
$("planProject").addEventListener("click", async () => { try { if (!$("projectGoal").value.trim()) throw new Error("Add a project goal/master brief before planning."); const p = await grantProviderAccess({ quiet: true }); await saveProject({ log: false }); await command("plan_project"); addLog("PLAN!", `Sent the protected project-start prompt to ${p.name}.`); } catch (e) { addLog("CRASH", e.message); } });
$("armWorkflow").addEventListener("click", async () => { try { const p = await grantProviderAccess({ quiet: true }); await saveProject({ log: false }); await command("arm"); addLog("ZAP!", `Arming the current ${p.name} thread.`); } catch (e) { addLog("CRASH", e.message); } });
$("pauseWorkflow").addEventListener("click", () => command("pause")); $("resumeWorkflow").addEventListener("click", () => command("resume")); $("refreshState").addEventListener("click", () => command("get_state")); $("resetSession").addEventListener("click", () => command("reset_session"));
$("changeCourse").addEventListener("click", async () => { try { const text = $("changeRequest").value.trim(); if (!text) throw new Error("Describe the course change first."); await grantProviderAccess({ quiet: true }); await command("change_course", { change_request: text }); addLog("PIVOT?", "Course-change review requested. No project commands will run until you approve the impact."); } catch (e) { addLog("CRASH", e.message); } });
$("finishProject").addEventListener("click", async () => { try { await grantProviderAccess({ quiet: true }); await command("finish_project"); addLog("CHECK!", "Final verification/closeout requested."); } catch (e) { addLog("CRASH", e.message); } });
$("approveButton").addEventListener("click", async () => { if (currentApprovalId) await command("approval", { approval_id: currentApprovalId, decision: "approve" }); });
$("rejectButton").addEventListener("click", async () => { if (currentApprovalId) await command("approval", { approval_id: currentApprovalId, decision: "reject" }); });
command("ping").catch(() => {}); setTimeout(() => command("get_state").catch(() => {}), 250);
